config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'

  resources :welcome  # notre ancien get 'welcome/:first_name' on a remplace :first_name par :id dans le controller, et la view, to: 'welcome#show' #route dynamique vers l URL cachee
  resources :team
  resources :contact
  resources :gossips
  resources :users
  resources :cities
  resources :comments

  resources :gossips do  #nested routes pour imbriquer nos gossips et nos comments
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#relation 1N avec User Comment et Like
    belongs_to :user
    has_many :comments
    has_many :join_table_gossip_tags
    has_many :tags, through: :join_table_gossip_tags #Relation NN entre Gossip et Tag d ou la necessite de passer par une table intermedaire table jointe.
	validates :title, length: {in:3..14} #on valide la presence du titre du gossip si ce dernier respecte une longueur comprise entre 3 et 14
    validates :content, presence: true #on impose la presence d un contenu pour valider le gossip
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :destroy, :show]

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
	  puts @gossips = Gossip.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @comments = Comment.all #nous avons besoin des comments pour les afficher dans le show gossis!!!
    @gossip = Gossip.find(params[:id])

  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)

    #on verifie que le formulaire envoie bien les params saisis code entre les puts $ non necessaire , mais qui nous permet de checker au debut 
    puts "$" * 60
    puts "ceci est le contenu de params et signifie que le formulaire pointe bien sur create :"
    puts params
    puts "$" * 60

    #le code suivant est le code a rentrer dans $ rails c afin de creer en BDD un user test un gossip test qui a donc ce user associe. et on check si il y les rollbacks et si ca marche bien
    #u = User.new(first_name:"Sarah", last_name:"B", age:33, description:"unknowm", email:"sarah@sarah.com", city_id:City.all.sample.id)
    #u.save
    #@gossip = Gossip.new(title: params[:title], content: params[:content], user_id: u.id)
    #puis @gossip.save 
    #sil n y a pas de rollbacks notre save est bien effectue et notre @gossip sauve en BDD

    @gossip = Gossip.new(title: params[:title], content: params[:content], user: User.find_by(id: session[:user_id])) #pour le test user_id: 3 dans rails c on recoit le message g.errors.messages
 #=> {:user=>["must exist"], :title=>["is too short (minimum is 3 characters)"], :content=>["can't be blank"]}

    if @gossip.save # essaie de sauvegarder en base @gossip
      flash[:success] = "The super potin was succesfully saved !"
    # si ça marche, il redirige vers la page d'index du site
        redirect_to root_path #redirect_to va passer root GET    /   gossips#index cf $ rails routes | grep root

  else
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render :new
  end
end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])
  end

  def update #le formulaire d edition pointe ici ici ON ACTUALISE LE GOSSIP POUR L ENREGISTRER EN BDD
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
     
    #@model = Model.find(params[:id])
    #if @model.update(tes_params)
    #redirect_to @model
    #else
    #render :edit
   #end

       @gossip = Gossip.find(params[:id])
       if @gossip.update('title' => params[:title], 'content' => params[:content], 'user_id' => @gossip.user_id) #aide demandee
        flash[:success] = 'Potin bien mis à jour !'
        redirect_to @gossip  # notre gossips#show merci rails routes |grep gossips... mon meilleur ami
      else
      render :edit
      end
  end


  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      flash[:success] = 'Le potin a ete detruit avec succes!'
      redirect_to gossips_path #correspond a gossips#index ($rails routes | grep gossips)

  end
  private

  

  def authenticate_user
    unless session[:user_id] #ou cuurent_user
      flash[:error] = "Vous devez etre connecte pour acceder au contenu du boat" #notre flash error doit etre dans le view layout application.html.erb
      redirect_to new_session_path #donc le log in form
    end
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
	#pas necessaire ici je crois mais je le laisse au cas ou...flemme de tester fatigue, necessaire sure dans sessions_helper.erb
	def current_user
    User.find_by(id: session[:user_id])
  end
end

app/views/gossips/edit.html.erb
<html>

  <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p> Nous n avons pas pu mettre a jour ce potin pour les raisons suivantes :  </p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Modifie ce potin! </h1>
    <p class="lead">Tu peux modifier le titre et le contenu si tu le souhaites</p>
  </div>
</div>

<!-- Comme dans le premier formulaire_tag du view new.html.erb on renseigne cependant differement l action et la methode put ou patch qui sert a updater le formulaire cette fois ci-->
<%= form_tag url_for(action: 'update'), method: "put" do %>

  <%= label_tag 'Titre du potin : ' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Contenu du potin : ' %>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Modifier Gossip" %>

<% end %>

app/views/gossips/index.html.erb
<html>
<!-- On met le flash ici pour que dans la view qui affiche les gossips puisse s executer les codes flash du controller gossips-->
<% flash.each do |key, value| %>
  <div class="alert alert-success" role="alert">
    <%= value %>
  </div>
<% end %>
<body>
  <h1> --- WELCOME MOUSSAILLON --- </h1>
  <% if session[:user_id]%> 
  <h1> BIENVENUE A BORD DU GOSSIP PROJECT <%= current_user.first_name %>  </h1>
   <%end%>

  <!-- ici on cree le bouton qui clique va nous amener au formulaire, on aurait pu mettre new_gossip_path avec les sigles -->
   <%= button_to "Je cree un nouveau potin", "gossips/new", :id => "open-contacts-dialog-btn", :class => "btn btn-primary btn-lg", :method => :get %>

  

  <div class="container" style="display: flex; flex-wrap: wrap; justify-content: space-around; padding-top: 120px">
    <% @gossips.each do |gossip| %>
      <div class="card text-white bg-secondary mb-3" style="width: 30rem;">
        <div class="card-header"> Auteur : <%= User.find(gossip.user_id).first_name %>  <%= User.find(gossip.user_id).last_name %> </div>
        <div class="card-body">
          <h5 class="card-title">Titre du gossip : <%= gossip.title %></h5>
               <%= link_to 'Voir', gossip_path(:id => gossip.id), class: 'btn btn-secondary bg-info' %>
          <div class="card-footer"> </div>
        </div>
      </div>
    <% end %>
  </div>

</body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>Créer un potin</title>
  </head>

 <% if @gossip.errors.any? %>
 <!-- Alerte Bootstrap-->
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <body>
    <h1>Crée un potin !</h1>
    <p>Balance ton potin via le formulaire ci-dessous</p>

<!-- Formulaire form_tag du https://launchschool.com/books/demystifying_rails/read/form_helpers#formtag -->
    
 <!--Le formulaire va POINTER vers la methode #create dans le controller gossips Jamy, nous dit c'est pas super intuitif, mais PAR CONVENTION le POST de création va à /gossips et non pas /gossips/new -->

 <%= form_tag url_for(action: 'create'), method: "post", class: "form" do %>

 <!-- L authenticity token va nous permettre de securiser la requete -->
   <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

      <%= label_tag 'Titre du potin' %>
      <%= text_field_tag 'title'%>
      <br/> <br/>
      <%= label_tag 'Contenu du potin' %>
      <%= text_area_tag 'content'%>
      <br/> <br/>
      <%= submit_tag "Create Gossip" %>
    <% end %>
 </body>>
</html>

app/views/gossips/show.html.erb
<html>

<!-- On met le flash ici pour que dans la view qui affiche le gossip en question puisse s executer les codes flash du controller gossips (dans la methode update qui renvoie a view gossip show.html.erb)-->
<% flash.each do |key, value| %>
  <div class="alert alert-success" role="alert"> <%= value %> </div>
<% end %>

  <title>
      Page potin
  </title>

  <body>

<div class="jumbotron">

 <h3>PAGE POTIN </h3>
  <p>Voici la page du potin n <%=@gossip.id%>, cree le <%= @gossip.created_at %></p> 

  <!-- Affiche le titre et le contenu du potin-->
  <p class="lead"> Titre : <%=@gossip.title %> </p>
  <p class="lead"> Contenu : <%= @gossip.content %> </p>
  
  <!-- Affiche le nom de l auteur et le lien route "../users/#{@gossip.user_id}" : 2 eme facon de l ecrire-->
   <p> Auteur :  <%= link_to "#{User.find(@gossip.user_id).first_name} #{User.find(@gossip.user_id).last_name}", user_path(:id => @gossip.user.id) %> </p>


  <!-- Affiche la ville de l auteur et le lien route "../cities/#{User.find(@gossip.user_id).city_id}"  : 2eme facon de l ecrire-->
  <p> Ville : <%= link_to User.find(@gossip.user_id).city.name, "../cities/#{User.find(@gossip.user_id).city_id}" %> </p>
  


<!--CONDITIONS POUR QUE USER PUISSE DELETE OU EDIT UN POTIN : si user logge et si auteur du gossip-->
  <% if session[:user_id]%> 
      <% if current_user.id == @gossip.user_id %>

  <!-- Lien pour editer le potin, qui nous envoie sur le affichage du formulaire d edition le Update du CRUD donc Get pointe vers controller gossips et execute la methode #edit qui execute la view edit.html.erb-->
  <%= link_to 'Editer le potin', edit_gossip_path, class: 'btn btn-primary' %>
<!--on renvoie ici sur gossips#show soit afficher une ressource precise comme le potin vient d etre supprime rien n apparait et la methode du controller gossips update continue d etre executee en redirigeant vers redirect_to gossips_path #correspond a gossips#index ($rails routes | grep gossips) et on a tous nos gossips - celui supprime en BDD
-->
  <%= link_to 'Supprimer le potin', gossip_path(@gossip), method: :delete, class: 'btn btn-danger' %>
      <%end%>
  <%end%>
  <hr class="my-4">
   <!-- AJout du lien pour creer un commentaire donc ca pointe vers new MAIS COMME PASSE PAR un gossip particulier on va devoir appliquer nested resources pour pouvoir afficher la liste des commentaires mais seulement ceux liés à un gossip donné. Tu veux pouvoir créer un commentaire en le liant à un gossip donné.-->
  <%= link_to 'Ajouter un nouveau commentaire', "/gossips/#{@gossip.id}/comments/new", class: 'btn btn-primary btn-sm' %> <br/> <br/> <br/>
<!--"/gossips/#{@gossip.id}/comments/new" est l equivalent de new_gossip_comment_path -->




   <a href="<%= gossips_path %>"class="btn btn-primary">Revenir à la page des potins</a>
   
   <% @comments.each do |comment| %> <!-- comme on fait une boucle, pour chaque commentaire on aura les boutons supprime et edite et les focnstions qui vont avec-->
    <% if @gossip.id == comment.gossip_id %>
      <li class="list-group-item list-group-item-primary"><%= current_user.first_name %> Commentaire : <br><%= comment.content %>
        <p> <br>
         <% if session[:user_id]%> <!-- si le hash est bien existant dans le navigateur  -->

         <!--Conditions pour supprimer ou editer un commentaire, etre l auteur du gossip ou du commentaire -->
            <% if current_user.id == @gossip.user_id || current_user.id == comment.user_id%>

        <!-- liens boutons pour supprimer et editer et pointent vers la route du commentaire specifique du gossip specifique pour lui appliquer la methode#edit dans le controller comments et la methode destroy-->
              <%= link_to 'Editer le commentaire', "/gossips/#{@gossip.id}/comments/#{comment.id}/edit", class: 'btn btn-primary btn-sm' %> 
              <%= link_to 'Supprimer le commentaire', "/gossips/#{@gossip.id}/comments/#{comment.id}", method: :delete, class: 'btn btn-danger btn-sm' %>
            <%end%>
          <%end%>
        </p>
      </li>
    <% end %>
  <% end %>
</div>    


     
  </body>
</html>