config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'

  resources :welcome  # notre ancien get 'welcome/:first_name' on a remplace :first_name par :id dans le controller, et la view, to: 'welcome#show' #route dynamique vers l URL cachee
  resources :team
  resources :contact
  resources :gossips
  resources :users
  resources :cities
  resources :comments

  resources :gossips do  #nested routes pour imbriquer nos gossips et nos comments
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
		has_many :users #Relation 1N entre user et city (user aura belongs_to :city)
end

app/models/comment.rb
class Comment < ApplicationRecord
	#un commentaire a une relation 1N avec User Gossip et Like 
	belongs_to :user
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#relation 1N avec User Comment et Like
    belongs_to :user
    has_many :comments
    has_many :join_table_gossip_tags
    has_many :tags, through: :join_table_gossip_tags #Relation NN entre Gossip et Tag d ou la necessite de passer par une table intermedaire table jointe.
	validates :title, length: {in:3..14} #on valide la presence du titre du gossip si ce dernier respecte une longueur comprise entre 3 et 14
    validates :content, presence: true #on impose la presence d un contenu pour valider le gossip
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
	belongs_to :gossip #meme si elle sert de table jointe elle nest qu en relation 1N avec Gossip et Tag alors quentre eux ils sont NN
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user #relation 1N entre Like et user , et avec comment et gossip
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true #mis en optional pour pouvoir faire Like.create sans avoir derreurs et sans necessairement avoir de relation obligatoire
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	#ici on implemente la methode class_name
	belongs_to :sender, class_name: "User" #1message appartient a un sender qui en fait une class User grace a la methode class_name
	belongs_to :recipient, class_name: "User" #1message appartient a un receveur qui est en fait une classe User ""
end

app/models/tag.rb
class Tag < ApplicationRecord
	#Tag a une relation NN avec Gossip donc on passe par la table jointe
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	#3eme etape d implementation de la methode class_name pour les messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :recieved_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	#ces messages envoyes et recus correspondent a la colonne sender_id et recipient_id de la table private_messages
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } #on impose le mail de l utilisateur, son format et le fait qu il n en existe 1 seul en bdd
	has_secure_password #sollicite la gem bcrypt pour hasher le password en clair
	validates :password_digest, presence: true, length: {minimum: 6}
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
        # Méthode qui récupère tous les users et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
        # Méthode qui récupère le user concerné et l'envoie à la view show (show.html.erb) pour affichage

    @user = User.find(params[:id])
  end

  def new

        # Méthode qui crée un user vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)

    @user = User.new
  end

  def create
    # Méthode qui créé un user à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige ici vers la méthode index ici de gossips pour afficher tous les gossips (pour afficher le potin créé)



    #CQFD
    #city = City.find_or_create_by(name: params[:city], zip_code: params[:zip_code])
    #@user = User.new(first_name: params[:first_name], last_name: params[:last_name], city: city, description: params[:description], age: params[:age], email: params[:email], password: params[:password], city_id: City.last.id) 
    @user = User.new(email: params[:email], password: params[:password], first_name: params[:first_name], last_name: params[:last_name], city_id: City.first.id)        
    if @user.save
      flash[:success] = 'Le profil a ete cree avec succes!'
      redirect_to gossips_path #gossips#index
    else
      render :new
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
	#pas necessaire ici je crois mais je le laisse au cas ou...flemme de tester fatigue, necessaire sure dans sessions_helper.erb
	def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

<!-- Ajout CDN BOOTSTRAP -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  
    <!-- Ajout Header et Navbar -->

    
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-primary">
          <a class="navbar-brand" href="#">Gossip Boat</a>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                   <%= link_to "Accueil", gossips_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Contact", contact_index_path, class: "nav-link" %> <!-- Le link_to genere lequivalent de la balise HTML a, le path correspond au prefix de la route + path l equivalent du href pour chercher l URL correspondante-->
                </li>
                <li class="nav-item">
                   <%= link_to "Team", team_index_path, class: "nav-link" %>
                </li>
              </ul>
            </div>  
    
       <div>
    <!-- ul pour le login -->
          <ul class= "nav navbar-nav navbar-right">
              <% if current_user == nil %> <!-- si pas connexion detectee = pas de hash session donc renvoie nil et pas l objet user    curent_user  <==> User.find_by(id: session[:user_id]-->
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
              User
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
              <a class="dropdown-item" href="/users/new">Sign up</a> <!-- notre lien vers le formulaire tag qu on retrouve dans le new.html.erb du controller users-->
              <a class="dropdown-item" href="/sessions/new">Log in</a> <!--notre lien vers le formulaire de Log in qu o retrouve dans la view new.html.erb du controller sessions-->
            </div>
            </div>
          <% end %>

           <li class="nav-item">
          <% if current_user %> 
          <!-- on appelle la methode destroy du controller sessions-->
            <%= link_to "Se deconnecter", session_path(session.id), :class => "nav-link", method: :delete %>
          <% end %>
           </li>
          </ul>
      </div>

      </nav>





    <%= yield %>

  
</html>